# nastaveni ftp serveru
variables:
  FTP_URL: "erouska.betaversion.cz/"
  FTP_USERNAME: "erouska.betaversion.cz"
  FTP_PASSWORD: "Vz9]hd_!K2"

deploy:
  # nazev akce
  stage: deploy
  # natazeni docker image s git-ftp
  image: danielstrelec/git-ftp
  # spustime pozadovane skripty
  script:
    - git --version
    - git ftp --version
    # pouze pro vstupni deploy
    - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_URL
    # deploy posledniho commitu
    #- git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_URL
  # nastaveni spusteni - pouze na master vetvi
  only:
    - master
  # manualni spusteni, kdyz je zakomentovano spousti se automaticky
  #when: manual
