name: Deploy
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install global dependencies
        run: sudo npm install -g firebase-tools
      - name: Deploy to Firebase development
        if: github.ref == 'refs/heads/deploy'
        run: firebase deploy -P dev --token=${{ secrets.FIREBASE_DEV_TOKEN }} --non-interactive
        env:
          WEBSITE_URL: https://covid19cz.web.app/
      - name: Deploy to Firebase production
        if: github.ref == 'refs/heads/master'
        run: firebase deploy -P prod --token=${{ secrets.FIREBASE_PROD_TOKEN }} --non-interactive
        env:
          WEBSITE_URL: https://erouska.cz/
